### ISSUE TITLE
Support for fully qualified types

### ISSUE THREAD

**Issue by jjttjj** [s-expresso/clojobuf#1]
Hi
I'm pretty new to protocol buffers in general, so I might be wording something wrong here or missing why this isn't supported.

I believe you can use "fully qualified" types in `.proto` files by prefixing  a type name with a `.`, ie `.my.pb.ns.Msg`. At least, [I have seen this in the wild in some `.proto` files](https://github.com/cosmos/cosmos-sdk/blob/76f8ed1e868be87892efa54a9d411854ab4bbd01/proto/cosmos/tx/v1beta1/service.proto#L220-L221), though I cannot yet find specific protocol buffer docs explaining it.

Does clojobuf support this syntax?

For an example case, I added a different file `example2.proto` in the same directory as your example.proto:
```
syntax = "proto2";
package different.pb.ns;

import "example.proto";

message OtherMsg {
    optional .my.pb.ns.Msg imported_msg = 1;
    optional int32 some_field = 2;
}
```
but when I go to compile it with `clojobuf.core/protoc` I get 
```
Exception Cannot find a viable target: ("OtherMsg" ".my.pb.ns.Msg")
```

**Comment by st-cheewah** [comment]
Thanks for reporting this. I overlooked this fully qualified case and it is now fixed with git tag >= `v0.1.4`. Cheers!
